name: Build and push Docker Image to Docker Hub (trigger on merge to main)

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      
      - 
        name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      -
        name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      -
        name: Build with Maven and Jib
        run: ./mvnw -Pprod package verify jib:dockerBuild

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Logout
        run: docker logout
